apiVersion: apps/v1
kind: Deployment
metadata:
  name: workshop-deployment
  namespace: workshop-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: workshop-configmap
        - secretRef:
            name: workshop-secret