apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
  namespace: workshop-services
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: None  # Headless service. Omit this line if you don't need a headless service.
