apiVersion: v1
kind: Service
metadata:
  name: nginx-internal-loadbalancer
  namespace: workshop-services
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
