apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  namespace: workshop-services
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # The port the service will expose internally in the cluster
      targetPort: 80   # The port the NGINX container is listening on
      nodePort: 30001  # The port on each node's IP that will expose the service externally
