apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: deployment-rs-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
#      securityContext:
#        runAsUser: 1000  # Run containers as non-root user
#        runAsGroup: 1000  # Group ID for containers
#        runAsNonRoot: true  # Ensure containers do not run as root
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
