apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-file
  namespace: azure-pvcs
  annotations:
    volume.azure.com/file-share-name: my-custom-fileshare-name
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azure-file
  resources:
    requests:
      storage: 5Gi
