kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-managed-disk
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Premium_LRS
  diskName: my-custom-disk-name