# This is a SecretProviderClass example using user-assigned identity to access your key vault
# Service Connector sets up the Azure resource connection, users only need create the SecretProviderClass and workload resources
# For the variables to fill in, you may get their values from Service Connector Azure Portal


apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  namespace: secret-configmap-namespace
  name: sc-demo-keyvault-csi
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"                        # Set to true for using managed identity
    keyvaultName: kv-name  # Set to the name of your key vault
    # Array of objects that contain the key vault secret name and the type of the object
    objects:  |
      array:
        - |
          objectName: test-secret          # keyvault secret name
          objectType: secret
        - |
          objectName: stam-test
          objectType: secret

    tenantId: "SOME_ID"            # The tenant ID of the key vault